### ISSUE TITLE
`RuntimeError: out of bounds memory access`

### ISSUE THREAD

**Issue by elado** [kwonoj/swc-plugin-formatjs#48]
```js
import { transformSync } from "@swc/core";

const src = `
import { FormattedMessage } from "react-intl";

export function App() {
  return (
    <div>
      <FormattedMessage defaultMessage="Hello" description="Hello!" />
    </div>
  );
}
`;

const result = transformSync(src, {
  jsc: {
    parser: {
      syntax: "typescript",
      tsx: true,
    },
    transform: {
      react: {
        runtime: "automatic",
      },
    },
    experimental: {
      plugins: [
        [
          "SWC-plugin-formatjs",
          {
            idInterpolationPattern: "[sha512:contenthash:base64:6]",
            removeDefaultMessage: true,
          },
        ],
      ],
    },
  },
});

console.log(result);
```

```
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `SWC-plugin-formatjs` as js transform plugin at node_modules/SWC-plugin-formatjs/target/wasm32-wasi/release/swc_plugin_formatjs.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: <unknown>
   8: <unknown>', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.230.9/src/plugin.rs:228:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:241
            return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                            ^

Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `SWC-plugin-formatjs` as js transform plugin at node_modules/SWC-plugin-formatjs/target/wasm32-wasi/release/swc_plugin_formatjs.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: <unknown>
   8: <unknown>

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: <unknown>
   3: <unknown>
    at Compiler.transformSync (/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:241:29)
    at transformSync (/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:348:21)
    at file:///Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/transform.js:17:16
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  code: 'GenericFailure'
}
```

**Comment by KBrewz** [comment]
@elado did you find a workaround? I'm seeing the same `out of bounds memory access` error with an SWC plugin I'm working on, using Next 12. Next 13 works fine, just wondering if there's anything I can do to make it work with v12.
